### ISSUE TITLE
How is it meant to be used?

### ISSUE THREAD

**Issue by farmio** [danielnarey/elm-bulma-classes#1]
When I `import BulmaClasses` and want to use it in my view `div [ class BulmaClasses.nav.container ] []` I get an error 

> No module called `BulmaClasses.nav has been imported.

If i import it `exposing (nav)` it works fine but collides with Html.nav (and many more if I expose(..) )

**Comment by danielnarey** [comment]
Yeah, I would call that a bug in the Elm compiler. It's something I hope that the core language maintainers will fix, because I see no reason why the syntax `BulmaClasses.nav.container` should not be valid. The lower case should tell the compiler that you are looking for a record field rather than a module.

I've been testing BulmaClasses with my HtmlTree package (an alternative syntax on top of standard Elm Html), so I have not needed to expose everything in the Html namespace, which allows me to expose BulmaClasses without having conflicting names. If you want to be able to expose all of Html and also use BulmaClasses, here is a solution:

`import BulmaClasses as Bulma`

`myDiv =  div [ class (.container Bulma.nav) ] []`

OR:
`myDiv =  div [ class (Bulma.nav |> .container) ] []`

For nested record fields, you can do this:
`class (Bulma.nav |> .menu |> .state |> .isActive)`
