### ISSUE TITLE
Missing classes

### ISSUE THREAD

**Issue by rlefevre** [danielnarey/elm-bulma-classes#3]
Hi and thank you for the last release.

I noticed a few missing classes if you are interested to add them:

* `is-active` for anchors in `menu-list` items: http://bulma.io/documentation/components/menu/
* `is-left` and `is-right` for icons in forms: http://bulma.io/documentation/elements/form/

Regards

**Comment by danielnarey** [comment]
There have been further additions to Bulma since the last release of this package. I will no longer be updating the package as I am working on a different approach that will integrate Bulma classes into a complete UI design framework for Elm. Others are welcome to make additions to this package and submit a pull request.
